version: '3'

services:
  #  db:
  #    image: postgres
  #    ports:
  #      - "5432:5432"
  api:
    build: ./api
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
  #    depends_on:
  #      - db
  #  web:
  #    build: ./web
  #    command: ["npm", "start"]
  #    volumes:
  #      - ./web:/app/web
  #      - node-modules:/app/web/node_modules
  #    ports:
  #      - "3000:3000"
  #    environment:
  #      - NODE_ENV=development

#volumes:
#  node-modules:
